### ISSUE TITLE
Bump to PHPUnit 11 :pray: 

### ISSUE THREAD

**Issue by TomasVotruba** [lean-book-tools/phpunit-cleaner-result-printer#12]
Hi Matthias,

I'm working on book upgrade to Rector 2.0 :tada: 
https://github.com/rectorphp/rector-book/pull/225

Yet it requires php-parser 5 + PHPUnit 11.
I was looking into bumping this package, but failed. Could I ask you to update this one to PHPUnit 11? It would be great help and make upgrade of book doable :pray:

**Comment by TomasVotruba** [comment]
This is full error report when I run the ` php vendor/bin/generate-manuscript --ansi` in the book, if it helps:

```bash
None of the line fixers was able to reduce line 13 to the maximum length of 72. Full resource contents:  
                                                                                                           
  F                                                                   1 /                                  
  1 (100%)                                                                                                 
                                                                                                           
  Time: 00:00.175, Memory: 42.00 MB                                                                        
                                                                                                           
  There was 1 PHPUnit test runner warning:                                                                 
                                                                                                           
  1) Bootstrapping of extension                                                                            
  LeanBookTools\CleanerResultPrinterExtension failed: Too few arguments to                                 
  function PHPUnit\Logging\TestDox\TestResultCollector::__construct(), 1                                   
  passed in                                                                                                
  vendor/lean-book-tools/phpunit-cleaner-result-printer/src/CleanerResultPrinterExtension.php              
  on line 35 and exactly 2 expected                                                                        
  #0                                                                                                       
  vendor/lean-book-tools/phpunit-cleaner-result-printer/src/CleanerResultPrinterExtension.php(35):         
  PHPUnit\Logging\TestDox\TestResultCollector->__construct()                                               
  #1 [internal function]:                                                                                  
  LeanBookTools\CleanerResultPrinterExtension->__construct()                                               
  #2                                                                                                       
  vendor/phpunit/phpunit/src/Runner/Extension/ExtensionBootstrapper.php(69):                               
  ReflectionClass->newInstance()                                                                           
  #3 vendor/phpunit/phpunit/src/TextUI/Application.php(419):                                               
  PHPUnit\Runner\Extension\ExtensionBootstrapper->bootstrap()                                              
  #4 vendor/phpunit/phpunit/src/TextUI/Application.php(132):                                               
  PHPUnit\TextUI\Application->bootstrapExtensions()                                                        
  #5 vendor/phpunit/phpunit/phpunit(104):                                                                  
  PHPUnit\TextUI\Application->run()                                                                        
  #6 vendor/bin/phpunit(122): include('...')                                                               
  #7 {main}                              
```
